/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:81d1e7c8ca87b27e57ec3baae0722c82:e4f22956df2ec7945308ba0f847561cb:64bd503133ec8fc3aa7eefa9c9033dc9$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class SpriteSheet
	{
		public const string Background = "Background";
		public const string Capguy_turn_0001 = "capguy/turn/0001";
		public const string Capguy_turn_0002 = "capguy/turn/0002";
		public const string Capguy_turn_0003 = "capguy/turn/0003";
		public const string Capguy_turn_0004 = "capguy/turn/0004";
		public const string Capguy_turn_0005 = "capguy/turn/0005";
		public const string Capguy_turn_0006 = "capguy/turn/0006";
		public const string Capguy_turn_0007 = "capguy/turn/0007";
		public const string Capguy_turn_0008 = "capguy/turn/0008";
		public const string Capguy_turn_0009 = "capguy/turn/0009";
		public const string Capguy_turn_0010 = "capguy/turn/0010";
		public const string Capguy_turn_0011 = "capguy/turn/0011";
		public const string Capguy_turn_0012 = "capguy/turn/0012";
		public const string Capguy_walk_0001 = "capguy/walk/0001";
		public const string Capguy_walk_0002 = "capguy/walk/0002";
		public const string Capguy_walk_0003 = "capguy/walk/0003";
		public const string Capguy_walk_0004 = "capguy/walk/0004";
		public const string Capguy_walk_0005 = "capguy/walk/0005";
		public const string Capguy_walk_0006 = "capguy/walk/0006";
		public const string Capguy_walk_0007 = "capguy/walk/0007";
		public const string Capguy_walk_0008 = "capguy/walk/0008";
		public const string Capguy_walk_0009 = "capguy/walk/0009";
		public const string Capguy_walk_0010 = "capguy/walk/0010";
		public const string Capguy_walk_0011 = "capguy/walk/0011";
		public const string Capguy_walk_0012 = "capguy/walk/0012";
		public const string Capguy_walk_0013 = "capguy/walk/0013";
		public const string Capguy_walk_0014 = "capguy/walk/0014";
		public const string Capguy_walk_0015 = "capguy/walk/0015";
		public const string Capguy_walk_0016 = "capguy/walk/0016";
		public const string Cowboy_Celebrate_Celebrate_01 = "cowboy/Celebrate/Celebrate_01";
		public const string Cowboy_Celebrate_Celebrate_02 = "cowboy/Celebrate/Celebrate_02";
		public const string Cowboy_Celebrate_Celebrate_03 = "cowboy/Celebrate/Celebrate_03";
		public const string Cowboy_Celebrate_Celebrate_04 = "cowboy/Celebrate/Celebrate_04";
		public const string Cowboy_Celebrate_Celebrate_05 = "cowboy/Celebrate/Celebrate_05";
		public const string Cowboy_Celebrate_Celebrate_06 = "cowboy/Celebrate/Celebrate_06";
		public const string Cowboy_Celebrate_Celebrate_07 = "cowboy/Celebrate/Celebrate_07";
		public const string Cowboy_Celebrate_Celebrate_08 = "cowboy/Celebrate/Celebrate_08";
		public const string Cowboy_Celebrate_Celebrate_09 = "cowboy/Celebrate/Celebrate_09";
		public const string Cowboy_Celebrate_Celebrate_10 = "cowboy/Celebrate/Celebrate_10";
		public const string Cowboy_Celebrate_Celebrate_11 = "cowboy/Celebrate/Celebrate_11";
		public const string Cowboy_Die_Die_01 = "cowboy/Die/Die_01";
		public const string Cowboy_Die_Die_02 = "cowboy/Die/Die_02";
		public const string Cowboy_Die_Die_03 = "cowboy/Die/Die_03";
		public const string Cowboy_Die_Die_04 = "cowboy/Die/Die_04";
		public const string Cowboy_Die_Die_05 = "cowboy/Die/Die_05";
		public const string Cowboy_Die_Die_06 = "cowboy/Die/Die_06";
		public const string Cowboy_Die_Die_07 = "cowboy/Die/Die_07";
		public const string Cowboy_Die_Die_08 = "cowboy/Die/Die_08";
		public const string Cowboy_Die_Die_09 = "cowboy/Die/Die_09";
		public const string Cowboy_Die_Die_10 = "cowboy/Die/Die_10";
		public const string Cowboy_Die_Die_11 = "cowboy/Die/Die_11";
		public const string Cowboy_Die_Die_12 = "cowboy/Die/Die_12";
		public const string Cowboy_Idle = "cowboy/Idle";
		public const string Cowboy_Jump_Jump_01 = "cowboy/Jump/Jump_01";
		public const string Cowboy_Jump_Jump_02 = "cowboy/Jump/Jump_02";
		public const string Cowboy_Jump_Jump_03 = "cowboy/Jump/Jump_03";
		public const string Cowboy_Jump_Jump_04 = "cowboy/Jump/Jump_04";
		public const string Cowboy_Jump_Jump_05 = "cowboy/Jump/Jump_05";
		public const string Cowboy_Jump_Jump_06 = "cowboy/Jump/Jump_06";
		public const string Cowboy_Jump_Jump_07 = "cowboy/Jump/Jump_07";
		public const string Cowboy_Jump_Jump_08 = "cowboy/Jump/Jump_08";
		public const string Cowboy_Jump_Jump_09 = "cowboy/Jump/Jump_09";
		public const string Cowboy_Jump_Jump_10 = "cowboy/Jump/Jump_10";
		public const string Cowboy_Jump_Jump_11 = "cowboy/Jump/Jump_11";
		public const string Cowboy_Run_Run_01 = "cowboy/Run/Run_01";
		public const string Cowboy_Run_Run_02 = "cowboy/Run/Run_02";
		public const string Cowboy_Run_Run_03 = "cowboy/Run/Run_03";
		public const string Cowboy_Run_Run_04 = "cowboy/Run/Run_04";
		public const string Cowboy_Run_Run_05 = "cowboy/Run/Run_05";
		public const string Cowboy_Run_Run_06 = "cowboy/Run/Run_06";
		public const string Cowboy_Run_Run_07 = "cowboy/Run/Run_07";
		public const string Cowboy_Run_Run_08 = "cowboy/Run/Run_08";
		public const string Cowboy_Run_Run_09 = "cowboy/Run/Run_09";
		public const string Cowboy_Run_Run_10 = "cowboy/Run/Run_10";
        
        public static string[] capguyTurnSprites = new [] {
            Capguy_turn_0001,
            Capguy_turn_0002,
            Capguy_turn_0003,
            Capguy_turn_0004,
            Capguy_turn_0005,
            Capguy_turn_0006,
            Capguy_turn_0007,
            Capguy_turn_0008,
            Capguy_turn_0009,
            Capguy_turn_0010,
            Capguy_turn_0011,
            Capguy_turn_0012
        };

        public static string[] capguyWalkSprites = new [] {
            Capguy_walk_0001,
            Capguy_walk_0002,
            Capguy_walk_0003,
            Capguy_walk_0004,
            Capguy_walk_0005,
            Capguy_walk_0006,
            Capguy_walk_0007,
            Capguy_walk_0008,
            Capguy_walk_0009,
            Capguy_walk_0010,
            Capguy_walk_0011,
            Capguy_walk_0012,
            Capguy_walk_0013,
            Capguy_walk_0014,
            Capguy_walk_0015,
            Capguy_walk_0016
        };
            
        public static string[] coyboyIdleSprites = new [] { Cowboy_Idle };
        public static string[] coyboyRunSprites = new [] { 
            Cowboy_Run_Run_01,
            Cowboy_Run_Run_02,
            Cowboy_Run_Run_03,
            Cowboy_Run_Run_04,
            Cowboy_Run_Run_05,
            Cowboy_Run_Run_06,
            Cowboy_Run_Run_07,
            Cowboy_Run_Run_08,
            Cowboy_Run_Run_09,
            Cowboy_Run_Run_10
        };
        public static string[] coyboyDieSprites = new [] { 
            Cowboy_Die_Die_01,
            Cowboy_Die_Die_02,
            Cowboy_Die_Die_03,
            Cowboy_Die_Die_04,
            Cowboy_Die_Die_05,
            Cowboy_Die_Die_06,
            Cowboy_Die_Die_07,
            Cowboy_Die_Die_08,
            Cowboy_Die_Die_09,
            Cowboy_Die_Die_10,
            Cowboy_Die_Die_11,
            Cowboy_Die_Die_12
        };
        public static string[] coyboyJumpSprites = new [] { 
            Cowboy_Jump_Jump_01,
            Cowboy_Jump_Jump_02,
            Cowboy_Jump_Jump_03,
            Cowboy_Jump_Jump_04,
            Cowboy_Jump_Jump_05,
            Cowboy_Jump_Jump_06,
            Cowboy_Jump_Jump_07,
            Cowboy_Jump_Jump_08,
            Cowboy_Jump_Jump_09,
            Cowboy_Jump_Jump_10,
            Cowboy_Jump_Jump_11
        };
	}
}